### ISSUE TITLE
Dropped items spinning very fast

### ISSUE THREAD

**Issue by Melagranata** [CreativeMD/ItemPhysicLite#12]
Seems like the problem is back.

- Minecraft 1.19.2
- Forge 43.2.0
- CreativeCore 2.9.3
- ItemPhysic Lite 1.5.2

Before submitting I tried starting the game with only CreativeCore and ItemPhysic Lite installed, and the problem persists, so I excluded the modpack i'm using from the potential causes.

**Comment by SheReyy** [comment]
Same issue here, if that speed is intended, it would be nice to have a config for it. It just feels unnatural for me.

**Comment by CreativeMD** [comment]
Should be fixed in the newest version, but it is for 1.19.3. I don't plan to support 1.19.2 anymore. Hope that is fine for you.

**Comment by GeggsLegs** [comment]
Many mods still do not support 1.19.3, Could you reconsider making a 1.19.2 version?

**Comment by CreativeMD** [comment]
Sorry, but no. You can use ItemPhysic Full, which does not have this issue in the version for 1.19.2
